name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'markdown_generator/talkmap.ipynb'
      - 'markdown_generator/talkmap.py'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # This workflow pushes to the repository

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.14"
        enable-cache: true

    - name: Generate talk map
      run: uv run --with python-frontmatter --with getorg --with geopy python markdown_generator/talkmap.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add talkmap/
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        git push
